apiVersion: apps/v1
kind: Deployment
metadata:
  name: beer-app
  namespace: beer-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: beer-app
  template:
    metadata:
      labels:
        app: beer-app
    spec:
      containers:
        - name: beer-app
          image: beer-app:latest
          imagePullPolicy: Never
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/beerdb
            - name: SPRING_DATASOURCE_USERNAME
              value: beeruser
            - name: SPRING_DATASOURCE_PASSWORD
              value: beerpass
          envFrom:
            - secretRef:
                name: s3-credentials
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: beer-app
  namespace: beer-app
spec:
  selector:
    app: beer-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
