apiVersion: v1
kind: Service
metadata:
  name: beer-app
  namespace: beer-app
spec:
  type: NodePort
  selector:
    app: beer-app
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30080
